-- dogo8me2 2025
return {
	Meta = {
		Name = "Default",
		Author = "pyxfluff",
		Description = "Administer's classic look.",

		AdministerVersionsSupported = "min:2.0.0;max:25.0.1",
		IsDark = true,

		IconPack = {
			Name = "fli-round",
			DownloadFrom = {
				ServerURL = "https://administer.notpyx.me",
				AssetID = 4,
			},
		},
	},

	UIGradients = {},
	UIStrokes = {},
	ImageButtons = {},
	ImageLabels = {},
	TextButtons = {},
	TextLabels = {},
	Frames = {
		QuickscanHome = {
			BackgroundColor = Color3.new(0.172549, 0.737255, 1),
			Transparency = 0
		}
	},
	ScrollingFrames = {},
	TextBoxes = {},
	-- work in friggin PROGRESS
}
